# Version du docker-compose
version: "3.7"
# Sections listant les différents container
services:
  next:
    build: .
    container_name: test_cypress
    hostname: test_cypress
    restart: always
    networks:
      - test_cypress_network
    volumes:
      - ./:./:rw
    ports:
      - 3000:3000
    command: npm run dev

# Section définissant les différents réseaux
networks:
  test_cypress_network : {}