# Version du docker-compose
version: "3.7"
# Sections listant les différents container
services:
  next:
    image: ghcr.io/leauhic/nexttest:latest
    container_name: test_cypress
    hostname: test_cypress
    restart: always
    networks:
      - test_cypress_network
    ports:
      - 3000:3000

# Section définissant les différents réseaux
networks:
  test_cypress_network : {}
  