name: Intall, build and test
run-name: ${{ github.actor }} Intall, build and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npmModules
      
      - name : Installation des dépendances
        run : npm install

      - name : Build
        run : npm run build
  

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npmModules
          
      - name: Test e2e
        run : npm run e2e:headless

      - name: Archive test video
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Video e2e
          path: |
            cypress/videos/*.mp4
