name: Build and push docker image
run-name: ${{ github.actor }} docker
on: push
jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1 

      - name: Cache register
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: nexttest:${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Publish Build to JFrog
        run: |
            docker login ${{ secrets.JF_URL }} -u${{ secrets.JF_LOGIN }} -p${{ secrets.JF_ACCESS_TOKEN }}
            docker push nexttest:${{ github.run_number }}
      - name: Publish Build to Github
        run: |
            docker login ${{ secrets.GIT_URL }} -u${{ secrets.GIT_LOGIN }} -p${{ secrets.GIT_TOKEN }} 
            docker push nexttest:${{ github.run_number }}