name: Build and push docker image
run-name: ${{ github.actor }} docker
on: push
jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to GitHub registry
        uses: docker/login-action@v2
        with:
          registry : ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: nexttest:${{ github.run_number }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-tag]
    steps:
      - name: prepare client
        run : sudo apt-get install -y openssh-client

      - name: prepare key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: connect, clone and launch
        run : |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVEUR_IP }} 'bash -i -c "sudo docker login ${{ secrets.GIT_URL }} -u ${{ github.actor }} -p${{ secrets.GIT_TOKEN }} && sudo docker stop test_cypress && sudo docker rm test_cypress && sudo docker run -d --name "test_cypress" -p 1234:3000 nexttest:${{ github.run_number }}"'