name: Build and push docker image
run-name: ${{ github.actor }} docker
on: push
jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1 

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: nexttest:${{ github.run_number }}
          outputs: type=docker,dest=/tmp/nexttest.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: /tmp/nexttest.tar
  deploy_on_jfrog:
    runs-on: ubuntu-latest
    needs: build-and-tag
    steps:          
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
        name: nexttest
        path: /tmp
     - name: Load Docker image
       run: |
          docker load --input /tmp/nexttest.tar
          docker image ls -a
     - name: Publish Build to JFrog
       run: |
            docker login ${{ secrets.JF_URL }} -u${{ secrets.JF_LOGIN }} -p${{ secrets.JF_ACCESS_TOKEN }}
            docker push nexttest:${{ github.run_number }}

  deploy_on_github:
    runs-on: ubuntu-latest
    needs: build-and-tag
    steps:          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
         name: nexttest
         path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/nexttest.tar
          docker image ls -a
      - name: Publish Build to Github
        run: |
            docker login ${{ secrets.GIT_URL }} -u${{ secrets.GIT_LOGIN }} -p${{ secrets.GIT_TOKEN }} 
            docker push nexttest:${{ github.run_number }}